# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ad531b64b6393862ab436b208d9449d5fc428e83a21cc3bd9e7ebdedd6010959fc2c2fa182d07c2af5d086d8a6968194b503b9eec876c2e326b28f36e8b26c7

test:
  secret_key_base: 9b72ee6bfed9f0b0f8ee6ad47cecb1697636bf5cf67c5b0da2587361d29d31021ce8286f3469906d5242c60b6a0263f9e7e434e67d289daf9a7c8a8a4ad92865

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
